import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@fortawesome/fontawesome-free/css/all.min.css';
import './globals.css';
import Sidebar from './components/home/Sidebar';
import { AppWrapper } from './context/activeHiveContext';
import { ActiveChatProvider } from './context/activeChatContext';
import { SessionProvider } from './components/SessionProvider';
import { auth0 } from '@/lib/auth0';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth0Session = await auth0.getSession();
  const session = {
    user: auth0Session?.user
      ? {
          sub: auth0Session.user.sub,
          email: auth0Session.user.email,
        }
      : undefined,
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider session={session}>
          <ActiveChatProvider>
            <AppWrapper>
              <div className="flex h-screen font-albert">
                <Sidebar />
                <main className="flex-1">{children}</main>
              </div>
            </AppWrapper>
          </ActiveChatProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
