import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@fortawesome/fontawesome-free/css/all.min.css';
import './globals.css';
import Sidebar from './components/home/Sidebar';
import { AppWrapper } from './context/activeHiveContext';
import { ActiveChatProvider } from './context/activeChatContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ActiveChatProvider>
          <AppWrapper>
            <div className="flex h-screen font-albert">
              <Sidebar />
              <main className="flex-1">{children}</main>
            </div>
          </AppWrapper>
        </ActiveChatProvider>
      </body>
    </html>
  );
}
