apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-llm-hives
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-llm-hives
  template:
    metadata:
      labels:
        app: service-llm-hives
    spec:
      imagePullSecrets:
        - name: do-registry
      containers:
        - name: service-llm-hives
          image: registry.digitalocean.com/hive-services-registry/service-llm-hives:REPLACE_WITH_SHA
          ports:
            - containerPort: 3003
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
            - name: SERVICE_LLM_HIVES
              value: 'http://service-llm-hives:3003'
            - name: RABBITMQ_HOST
              value: 'rabbitmq.messaging.svc.cluster.local'
            - name: RABBITMQ_PORT
              value: '5672'
            - name: RABBITMQ_USER
              value: 'user'
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
