name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Next.js globally
        run: npm install -g next

      - name: Create package.json with Next.js in root
        run: |
          echo '{
            "name": "hive-root",
            "private": true,
            "dependencies": {
              "next": "^14.0.0"
            }
          }' > package.json
          npm install

      - name: Install dependencies for front-end
        run: |
          cd ./apps/front-end
          npm install

      - name: Build Next.js app
        run: |
          cd ./apps/front-end
          npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-params: '--prod'
          working-directory: ./apps/front-end
