name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Navigate to microservice directory
        run: cd apps/service-llm-hives/

      - name: Build the Docker image for service-llm-hives
        run: |
          cd apps/service-llm-hives/
          docker build --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t ${{ secrets.DOCKER_USERNAME }}/service-llm-hives:${{ github.sha }} .

      - name: Push the Docker image for service-llm-hives
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/service-llm-hives:${{ github.sha }}

      - name: Deploy to server
        run: |
          # Example deployment using SSH
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Pull latest image for service-llm-hives
            docker pull ${{ secrets.DOCKER_USERNAME }}/service-llm-hives:${{ github.sha }}
            
            # Stop and remove existing container (optional)
            docker stop service-llm-hives || true
            docker rm service-llm-hives || true

            # Run the new container for service-llm-hives
            docker run -d -p 3000:3000 --name service-llm-hives ${{ secrets.DOCKER_USERNAME }}/service-llm-hives:${{ github.sha }}
          EOF
