name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
        working-directory: ./apps/front-end
      - name: Run unit tests
        run: npm test
        working-directory: ./apps/front-end
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_PASSWORD }}

      - name: Build and push api-gateway image
        run: |
          docker build --platform linux/amd64 -t registry.digitalocean.com/hive-services-registry/api-gateway:${{ github.sha }} ./apps/api-gateway/
          docker push registry.digitalocean.com/hive-services-registry/api-gateway:${{ github.sha }}

      - name: Build and push service-user image
        run: |
          docker build --platform linux/amd64 -t registry.digitalocean.com/hive-services-registry/service-user:${{ github.sha }} ./apps/service-user/
          docker push registry.digitalocean.com/hive-services-registry/service-user:${{ github.sha }}

      - name: Build and push service-llm-hives image
        run: |
          docker build --platform linux/amd64 --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t registry.digitalocean.com/hive-services-registry/service-llm-hives:${{ github.sha }} ./apps/service-llm-hives/
          docker push registry.digitalocean.com/hive-services-registry/service-llm-hives:${{ github.sha }}

      - name: Build and push service-llm-responses image
        run: |
          docker build --platform linux/amd64 --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t registry.digitalocean.com/hive-services-registry/service-llm-responses:${{ github.sha }} ./apps/service-llm-responses/
          docker push registry.digitalocean.com/hive-services-registry/service-llm-responses:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig and deploy
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f ./k8s --validate=false
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Update Kubernetes manifests with new image tags
        run: |
          sed -i "s|registry.digitalocean.com/hive-services-registry/api-gateway:.*|registry.digitalocean.com/hive-services-registry/api-gateway:${{ github.sha }}|g" ./k8s/api-gateway-deployment.yaml
          sed -i "s|registry.digitalocean.com/hive-services-registry/service-user:.*|registry.digitalocean.com/hive-services-registry/service-user:${{ github.sha }}|g" ./k8s/service-user-deployment.yaml
          sed -i "s|registry.digitalocean.com/hive-services-registry/service-llm-hives:.*|registry.digitalocean.com/hive-services-registry/service-llm-hives:${{ github.sha }}|g" ./k8s/service-llm-hives-deployment.yaml
          sed -i "s|registry.digitalocean.com/hive-services-registry/service-llm-responses:.*|registry.digitalocean.com/hive-services-registry/service-llm-responses:${{ github.sha }}|g" ./k8s/service-llm-responses-deployment.yaml

      - name: Rollout restart deployments
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl rollout restart deployment api-gateway
          kubectl rollout restart deployment service-user
          kubectl rollout restart deployment service-llm-hives
          kubectl rollout restart deployment service-llm-responses

      - name: Verify pods status
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl get pods

      - name: Build and push K6 load test image
        run: |

      - name: Run K6 load test jobs
        run: |
