name: Load Testing with k6

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL for testing'
        required: false
        default: 'https://api.hive-app.nl'
      test_file:
        description: 'Test file to run'
        required: false
        default: 'health-check.js'

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test
        run: |
          cd apps/k6-tests
          k6 run tests/${{ github.event.inputs.test_file || 'health-check.js' }} \
            --env API_BASE_URL=${{ github.event.inputs.target_url || 'https://api.hive-app.nl' }}

      - name: Upload k6 results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: k6-results
          path: apps/k6-tests/results/
