name: Production Health Monitoring

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run Health Monitoring in k6 Cloud
        working-directory: apps/k6-tests
        run: |
          k6 cloud --exit-on-running tests/production-health-monitor.js \
            --env API_BASE_URL=https://api.hive-app.nl
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
